### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by garrett** [kejbaly2/devconfcz#1]
DevConf needs a new logo.

Requirements:

- Keep the same concept of a future-predicting crystal ball
- Horizontal version
- Vertical version (squareish)
- Degrades to black and white
- Able to be used on a website, t-shirts, flyers, stickers, banners and whatever other places where needed
- Could be modified to include location and/or year

--

For reference, here is the existing logo:

![devconfcz-logo](https://cloud.githubusercontent.com/assets/10246/16913464/ccdd7f52-4cea-11e6-866e-c8ce0abc403d.png)

**Comment by garrett** [comment]
After going through a lot of open source geometric sans serif typefaces that could reflect the feel of previous DevConf logos, yet be slightly different, I've found that [Monterserrat](https://www.google.com/fonts/specimen/Montserrat) seems to be a good starting point.

One requirement for this idea was to select a typeface with a near-geometrically perfect O, so we could swap it out with a stylized version based on a circle for a crystal ball, integrating the graphic into the type itself.

Both vertical and horizontal versions are included.

I've also added the location (written out) and the year below it, with the year truncated to a tick mark and the last two digits.
  
![devconf-sketches](https://cloud.githubusercontent.com/assets/10246/16912728/39e1f07e-4ce6-11e6-8d6a-df21e0e6950e.png)

In addition, I've made a quick pass at what a DevConf in the USA might look like in this style.

![devconf-sketches-usa](https://cloud.githubusercontent.com/assets/10246/16912731/3e8f6b24-4ce6-11e6-8f7d-b61040ab0b07.png)

Please note that these are rough drafts. Kerning would need to be adjusted, and the glyphs (each letter) would need to be further tweaked. Also, we'd need to figure out how to integrate color and perhaps spiff up the logo a bit more too.

But this could possibly be a starting point, if liked. :smile:

**Comment by garrett** [comment]
Here's a modification with tweaked glyphs and color:

![devconf-colorstyle](https://cloud.githubusercontent.com/assets/10246/16945425/4b005f98-4da5-11e6-8478-69e2b807e34e.png)

Same, in vertical:

![devconf-colorstyle-vert](https://cloud.githubusercontent.com/assets/10246/16945540/b8d3129a-4da5-11e6-82cb-24903cbbad5d.png)

To look like a crystal ball, the color probably needs to be blueish to some degree. I decided to try a more purple shade of blue for something different, and to inject a bit of red (Red Hat) into the blue (Fedora).

Looking for feedback (@kejbaly2).

**Comment by garrett** [comment]
Here's a variant on a dark background with a blue that's based on Fedora's blue (but a lighter shade to contrast the darkness) and an stroke around the crystal ball:

![devconf-colorstyle-vert-dark-blue](https://cloud.githubusercontent.com/assets/10246/16947229/24429e1c-4dae-11e6-93a2-e2eaa4a09169.png)

**Comment by jhadvig** [comment]
I like the logo, but really not fan of the [last](https://github.com/kejbaly2/devconfcz/issues/1#issuecomment-233595541) color pallet. The purple one is kinda nice though :+1:

**Comment by garrett** [comment]
Here's a mod for the dark one, where I darkened the background a little (to `#cccccc`) to make the purple pop a bit more (without going too light for the "DEV").

![devconf-colorstyle-vert2](https://cloud.githubusercontent.com/assets/10246/16948456/07cdfaae-4db5-11e6-9d7b-99d95f0b698c.png)

**Comment by garrett** [comment]
I added a really rough sketch of what this logo might look like in context of a website (a really rough and thrown together version of what a website for DevConf might look like) in issue #4.

**Comment by kejbaly2** [comment]
Personally, i'm digging the blue variant more than the purple.

**Comment by kejbaly2** [comment]
Part of the original 'branding' was the .CZ; what if we kept that, somehow. eg, 

DevConf.CZ ... DevConf.US DevConf.DE or whatever other country code the event might be in

Writing CZECH REPUBLIC is more accurate than just CZECH; but it's so long... and not nerdy like using top-level domains is. 

Not sure what to do with the '17 though... anyway...

**Comment by kejbaly2** [comment]
I'm not sure about the 

DEV
CONF

layout either... it feels off, somehow. 

DEV
CONF.CZ 

would be even worse...

 DEV '17
CONF.CZ

hrm.....

**Comment by jhadvig** [comment]
What about:

DEVCONF
CzechRepublic

Menine that the CzechRepublic font size will fit to the width of the DEVCONF header ?

**Comment by kejbaly2** [comment]
https://cloud.githubusercontent.com/assets/3764092/16982189/d38cd2fa-4e6e-11e6-820f-c96084f64be4.png  

with the '17 at the tail looks interesting

**Comment by kejbaly2** [comment]
Yea, 

DEVCONF'17
Czech Republic

could work

**Comment by garrett** [comment]
### Year and country (separate)

DevConf 'YY
COUNTRY

![devconf-17-cz](https://cloud.githubusercontent.com/assets/10246/16983984/183dc036-4e78-11e6-9790-439187541a02.png)

![devconf-17-us](https://cloud.githubusercontent.com/assets/10246/16983980/10f0e6c8-4e78-11e6-9946-fcba77090a8f.png)

---

### Country and year (together)

DevConf
COUNTRY 'YY

![devconf-cz17](https://cloud.githubusercontent.com/assets/10246/16983998/33f29b6c-4e78-11e6-8537-019822b80665.png)

![devconf-us17](https://cloud.githubusercontent.com/assets/10246/16984003/36f4fdbe-4e78-11e6-8d7c-f916aec78f72.png)

---

### City and year

DevConf
CITY 'YY

![devconf-brno17](https://cloud.githubusercontent.com/assets/10246/16984041/5acab5d0-4e78-11e6-8830-88844b50c0bb.png)

![devconf-portland17](https://cloud.githubusercontent.com/assets/10246/16984046/5d598f56-4e78-11e6-990b-c56b0fc90cb3.png)

_Note: I don't know where the venue would be within the USA, so I just used Portland as an example._

---

### Country abbreviation only

DevConf.TLD

![devconf-cz](https://cloud.githubusercontent.com/assets/10246/16984059/6a533cac-4e78-11e6-9b8a-256ba5845f25.png)

![devconf-us](https://cloud.githubusercontent.com/assets/10246/16984064/6e3ab138-4e78-11e6-9cb4-3ad600ded204.png)

**Comment by garrett** [comment]
(My opinion: The last post seems to be ordered from cluttered to uncluttered.)

**Comment by jhadvig** [comment]
I would go with the last suggested on. and above the country domain I would put abbreviation of the year in gray.

**Comment by garrett** [comment]
Having the date as you suggest is extremely cluttered and does not look good.

First, here's a correct version of the above, with the .CZ and .US scaled to between the median and baseline (as it was slightly off before):

![devconf-cz2](https://cloud.githubusercontent.com/assets/10246/16990002/ab45700e-4e96-11e6-9551-ed0e14b08d4f.png)

![devconf-us2](https://cloud.githubusercontent.com/assets/10246/16990074/f8d6838a-4e96-11e6-8e06-564c6c2d1c7d.png)

Here's the same, but with '17 tacked on in the top-left:

![devconf-cz2-17](https://cloud.githubusercontent.com/assets/10246/16990083/03b0e638-4e97-11e6-8a6f-7342587041e2.png)

![devconf-us2-17](https://cloud.githubusercontent.com/assets/10246/16990085/054c17b0-4e97-11e6-97d9-167162a5da86.png)

It's too busy and doesn't work.

Remember that the logo has to be rendered in smaller sizes and for different media (such as t-shirts, I bet). Here's an example of it scaled down to a tiny size:

![devconf-cz2-17-tiny](https://cloud.githubusercontent.com/assets/10246/16990399/29943f52-4e98-11e6-8bfa-3de024f0f578.png)

Also, it would mean someone would have to update the logo each and every year, with the correct font, and export it to all the appropriate media. In addition to ensuring it is done correctly, with everything updated to a newer timestamped version, it would also mean that any swag made for the previous year is invalidated (example: too many t-shirts printed for 2017 couldn't be redistributed in 2018).

**Comment by garrett** [comment]
Updated the super-sketchy website example w/ the new WIP logo @ https://github.com/kejbaly2/devconfcz/issues/4#issuecomment-233977435

I guess it makes sense to include it inline in this discussion too:

![devconf-colorstyle-website-mockup-2](https://cloud.githubusercontent.com/assets/10246/16991629/78efa470-4e9c-11e6-8592-f460cf78841a.png)

(FWIW: This is just a playground to show how the logo could look in a website design. It's not a website proposal. Parts might be used as inspiration for the actual website, but that's a different discussion.)

**Comment by garrett** [comment]
# Today's updates!

Based on feedback on the DevConf list, I've made another iteration with a simplified color palette.

This iteration features:

- fewer colors
- emboldening the DEV to highlight it and set it apart from CONF
- reworking of the embedded crystal ball to make it a bit more obvious as a crystal ball (based on the old logo)
- light and dark versions of each varaint
- versions that are plain, with the country spelled out, and with the country domain extension (.cz in this case)

I suggest that we drop the location and just have the plain DEVCONF as the logo, and treat the location, tagline, or anything else that might accompany it as an add-on (and come up with guidelines for that). The end result would be similar in some usages, but it would make talking about the official logo a bit easier, I think.

## Country spelled out
![devconf-weights-country](https://cloud.githubusercontent.com/assets/10246/17143303/3a6eafbe-5353-11e6-9e38-632f83942ae2.png)

## .CZ

![devconf-weights-cz](https://cloud.githubusercontent.com/assets/10246/17143314/468d9e0e-5353-11e6-9219-e0282ba2464e.png)

## Standalone logo
![devconf-weights](https://cloud.githubusercontent.com/assets/10246/17143335/56f47196-5353-11e6-866f-e40628611b0f.png)

## Purple version of the standalone logo

![devconf-weights-purple](https://cloud.githubusercontent.com/assets/10246/17143341/5d7deb8c-5353-11e6-8b9e-85347f99a09e.png)

---

Done in this slightly modified style, I think I'm partial to the purple. It feels more "magical" to me, which is what a crystal ball is about. Plus, the world already has so many blue logos; it'd be nice to have more purple ones. :grinning:

**Comment by garrett** [comment]
Modification of the last posted logo proposal with a slight stand for the crystal ball.

![devconf-weights-purple-ballstand](https://cloud.githubusercontent.com/assets/10246/17172370/167883c6-53f5-11e6-89a3-08da954ccaa2.png)

**Comment by deekej** [comment]
OK, the last one is almost perfect for me... :) The only thing that I wouls change there is the addition of .TLD as in previous posts. I still feel this is part of the logo legacy as well, and should be there.

Could you please try to add the .TLD (.cz, .us) to the last version of the logo, in both purple and grey colors? I would like to see how this would work out (or not).

Anyway, very nice work garrett, good job! :)

**Comment by garrett** [comment]
@deekej: Great! Yeah, I was thinking to keep the DEVCONF logo itself prestine, and use add-ons for different venues. Currently, the only venue is .cz, but there's a _possibility_ that it _might_ expand to .us (or even other places?) as well.

I'll make a .cz version and show what it could look like degraded to 1 color (and shades of grey too).

**Comment by garrett** [comment]
## same color .cz/.us

![devconf-crystal-cz](https://cloud.githubusercontent.com/assets/10246/17177724/0dff3b90-5413-11e6-8885-28ca37c5dab9.png)

![devconf-crystal-us](https://cloud.githubusercontent.com/assets/10246/17177726/10157aac-5413-11e6-911b-9498e7dbf599.png)

## grey .cz/.us

![devconf-crystal-cz-grey](https://cloud.githubusercontent.com/assets/10246/17177746/2098bab0-5413-11e6-986d-4e0506d3a280.png)

![devconf-crystal-us-grey](https://cloud.githubusercontent.com/assets/10246/17177751/21ddbe34-5413-11e6-80e4-5f6d2df91315.png)

## color .cz/.us

![devconf-crystal-cz-color](https://cloud.githubusercontent.com/assets/10246/17177755/28bd26c2-5413-11e6-925d-f5bb52b47a6d.png)

![devconf-crystal-us-color](https://cloud.githubusercontent.com/assets/10246/17177772/2d4e0ada-5413-11e6-9a6f-87a61e04d3fb.png)

---

## fully greyscale (for non-color printing)

(could also make .cz/.us in grey, but this depends on what is decided for the color version)

![devconf-crystal-cz-greyscale](https://cloud.githubusercontent.com/assets/10246/17177805/4885ac04-5413-11e6-8917-7c71edce812d.png)

![devconf-crystal-us-greyscale](https://cloud.githubusercontent.com/assets/10246/17177809/4b458202-5413-11e6-808c-164cf5bd0589.png)

## complete black-and-white (for even more limited printing)

(for this one, I had to drop the orb coloring completely, as it just looked wrong with a white orb and black reflections)

![devconf-crystal-cz-bw](https://cloud.githubusercontent.com/assets/10246/17177830/60842722-5413-11e6-8ce6-141f2044db95.png)

![devconf-crystal-us-bw](https://cloud.githubusercontent.com/assets/10246/17177833/639b7654-5413-11e6-85e8-2d7730b6b8f6.png)

**Comment by deekej** [comment]
I think that now it's perfect! :)

I would use the colorful .cz/.us extension, intead of the grey version. It nicely highlights the location. ;)

**Comment by kejbaly2** [comment]
I think until we actually have a non-CZ location we should keep the implied brand as DevConf.CZ; i'd like to go with the non-colorized .CZ this year (white/black, not gray) so we don't give anyone the wrong impression. In the future, once we actually have another event on the radar we can decide on colorized TLDs.

**Comment by deekej** [comment]
2 @kejbaly2: I see your point, makes sense. :) And are we gonna use the purple version now? (of crystal ball)

**Comment by kejbaly2** [comment]
What about the DevConf icon/avatar? It used to be the crystal ball, which now is part of the logo itself. I think folks want to keep the crystal ball. So, just pull out the new version of the crystal ball?

**Comment by kejbaly2** [comment]
![base_color_no_tld_icon](https://cloud.githubusercontent.com/assets/3764092/17768377/06285cf8-6534-11e6-8281-91dedc6a421b.png)

? 

hrm... Looking at it alone, is it obvious what it is supposed to represent?

**Comment by kejbaly2** [comment]
Or would we have the whole DevConf.CZ in square shape? I wonder how readable it is in small form?

**Comment by garrett** [comment]
@kejbaly2: the whole logo wouldn't work in 16×16 or 32×32 (or even much larger)

This graphic should never be used with the text; it should be standalone:

![devconf-globe-32](https://cloud.githubusercontent.com/assets/10246/17780046/34e16356-656a-11e6-9f01-e1ca0bfc860f.png)

![devconf-globe-64](https://cloud.githubusercontent.com/assets/10246/17780052/391aa522-656a-11e6-9dae-bfc0439a9392.png)

![devconf-globe-128](https://cloud.githubusercontent.com/assets/10246/17780056/3c786b8c-656a-11e6-9cc2-28fac2441ac5.png)

![devconf-globe-256](https://cloud.githubusercontent.com/assets/10246/17780064/408852e6-656a-11e6-9d0f-e7bcada4574b.png)

It still needs further optimization @ 32px and I need to work on the 16px version too.

The big difference is to accentuate the globe, as it doesn't need to serve the purpose of an O in this context.

**Comment by kejbaly2** [comment]
Once you're back Garrett, I'd like to finalize the icon - right now folks who see it are confused what it is. I've heard 'i thought it was a washing machine' and 'oh, it isn't a bowling ball? and other similar things or the sort. Not sure what exactly could be done. But ... worth experimenting.

**Comment by garrett** [comment]
Sure. Do you have any ideas or suggestions that you'd like me to try?

**Comment by kejbaly2** [comment]
All I have is a reference to the crystal ball used in the past... which is a bit more obviously a crystal ball.... :-/

![image](https://cloud.githubusercontent.com/assets/3764092/18350789/d51956da-75d7-11e6-8d50-a45b84f1c13c.png)

**Comment by kejbaly2** [comment]
Gonna close this out and create a new issue to focus just on the icon.
