### ISSUE TITLE
Missing call for action

### ISSUE THREAD

**Issue by eliskasl** [kejbaly2/devconfcz#11]
There is no outstanding button on the first page to allow you to submit your abstract (yet?).
Also, there is so much text and scrolling that the call for papers button in the cfp section can get easily overlooked or the reader will give up by the time he gets there.
Could the menu be perhaps displayed from the beginning rather than showing up after scrolling down half of the first page? It would certainly help set some expectations and allow for faster navigation.

**Comment by kejbaly2** [comment]
Good point, we definitely want to put a CfP submit button right on the landing page.

**Comment by kejbaly2** [comment]
Check stage

http://stage.devconf.cz/

**Comment by eliskasl** [comment]
I made a PR against your branch, used the logo color for the button, removed redundant text and changed size (maybe could be a bit smaller). Have a look when you have time.

**Comment by kejbaly2** [comment]
merged; it might change still, but looks good to me for now. Thanks
