### ISSUE TITLE
Delete the Section about Scheduling and breaks

### ISSUE THREAD

**Issue by bexelbie** [kejbaly2/devconfcz#21]
I think this section is unneeded by attendees and is unnecessarily complex to convey.

If someone refuses to attend a conference without a guarantee that the sessions will start and end on the clock hours of their choice then they can choose not to attend DevConf.cz.

**Comment by kejbaly2** [comment]
Incidenty, I moved most of the CfP stuff to the CfP form itself. Better?

**Comment by kejbaly2** [comment]
reopen if you think it's still an issue.
