### ISSUE TITLE
Making website more readable

### ISSUE THREAD

**Issue by zerodayz** [kejbaly2/devconfcz#23]
I really liked the http://openshift.devconf.cz/ and it's font.
There are two things, readability is more important.

- Dynamic text when scrolling. Fade ins/ Title jump ins.
- Font is more readable.

**Comment by kejbaly2** [comment]
How's https://kejbaly2.github.io/devconfcz/index.html looking?

**Comment by kejbaly2** [comment]
If you disagree that it's not more readable after @garrett 's update, reopen.
