### ISSUE TITLE
Darker section heading background

### ISSUE THREAD

**Issue by frantisekz** [kejbaly2/devconfcz#37]
@lukassparrow pointed out that it might be better to have darker backgrounds for section headings. 
You can see it in action here: https://devconf.cz/stage/

I personally prefer darker backgrounds, what do you think?
@garrett @kejbaly2

**Comment by frantisekz** [comment]
Merged

**Comment by garrett** [comment]
I intentionally made it lighter, as the problem is that it's the same color as the button. If the header backgrounds are darker like this, then the button should be altered to be different enough.
