### ISSUE TITLE
Website refresh

### ISSUE THREAD

**Issue by garrett** [kejbaly2/devconfcz#4]
While the website is to be done later, I thought it would be a good idea to see how the logo might look in context in an example website.

**Comment by garrett** [comment]
Here's a quick mockup of what a website could look like, and what the latest WIP logo (at the time of writing @ https://github.com/kejbaly2/devconfcz/issues/1#issuecomment-233605476) could look like inside of this rough sketch:

![devconf-colorstyle-website-mockup](https://cloud.githubusercontent.com/assets/10246/16949480/54dd1c70-4dbb-11e6-8605-7f5debcbf818.png)

It's just a bunch of ideas kind of strung together — the site isn't really cohesive yet. The photo is one of mine from this year's DevConf, but tinted dark. The page might not use a photo on the front (or this high up if it does), and the front page should definitely have more content. Anyway, it's just a quick first pass to capture some ideas and provide some rough context for the logo in issue #1.

**Comment by garrett** [comment]
Some quick modifications (and dropped the photo for now, at least)

![devconf-colorstyle-website-mockup-2](https://cloud.githubusercontent.com/assets/10246/16991397/c05ec440-4e9b-11e6-97fb-93febeb615d8.png)

**Comment by kejbaly2** [comment]
RFC: Jakub Hadvig's first iteration of the site.
![web3](https://cloud.githubusercontent.com/assets/3764092/17765159/6b1a6e86-6524-11e6-992f-03f37576274a.png)
![web2](https://cloud.githubusercontent.com/assets/3764092/17765158/6b18f0ba-6524-11e6-8e28-33cc414dcc7b.png)

**Comment by bexelbie** [comment]
Looking only at the last two images, the fades in the first one make text hard to read.  The lack of fades in the second is better, but I don't understand where these colors came from.

I agree with Jan P that the pink is too much.  It doesn't match any of our branding colors (I believe it is safe to assume RH will always sponsor) and it clashes with our sponsor logos.

I am 100% in favor of getting rid of the heavy darkness of the old site, but this isn't a move in to that, it just changes the hues.

For top components, I like the incorporation of the line drawing of hte Petrov.  I think that is something we can easily do for any location, while a picture may be harder.

**Comment by kejbaly2** [comment]
![web3 1](https://cloud.githubusercontent.com/assets/3764092/17768038/9ba57ce0-6532-11e6-896c-9c77694d4d06.png)

**Comment by garrett** [comment]
Issues with the mockups above:

- Fonts are wrong (Montserrat is the headline font; body font is TBD, but it definitely shouldn't be that one, as it's a headline font being used for the body)
- Colors make it hard to read
- Colors are (probably — haven't checked yet) bad for colorblind people too
- Photos of people require checking with those prominently displayed for approval

Since we just have 2 weeks left, I suggest splitting the web design into two:

1. splash page with basic details and conservative styling for the audience of previous attendees (who want to know the date) and those submitting talks (who need info on how to do that)
2. full-blown site with more style

Rush a simple splash page, then work on the full site after the splash page launches.

**Comment by garrett** [comment]
Also, the tagline is `#define FUTURE` as a geeky C programmer's joke. As a result, it should be typeset in a monospace font like Source Code Pro (but it should probably really be the only monospace font on the site) to drive that point home. Otherwise it's improper language usage.

We did talk about "Define the Future" or "Defining the Future", but the conclusion was to stick with what's already there. (See issue #3.)

**Comment by frantisekz** [comment]
I personally prefer dark variant. The only problem in my opinion with it is readability of "about" paragraph text. Font color should be more bright IMO. Same goes for paragraph heading.

In pink color variant - i find it quiet difficult to optimize paragraph text color since there is dark pink going to white pink in the background. I wouldn't go for color transitions.

Regarding colorblind people - we can make simple javascript button which will load different css (and create cookie for the future visit) for colorblind people.

I think we can drop menu option "News" and make it visible directly at the front page. 
Or, apart from that, what do you think about Infinite scrolling design? I believe it would make sense here.

Also, we should advertise Android app on the website if we are going to have one.

**Comment by garrett** [comment]
Given the constraints of time and with our audience in mind, I've made a quick and simple splash page mockup that could work as an interim solution to inform people about DevConf.cz 2017 and allow them to submit papers.

![devconf-website-splash](https://cloud.githubusercontent.com/assets/10246/17769450/f3b246c4-6538-11e6-815d-c7f5eb345d2c.png)

SVG source is at https://people.redhat.com/glesage/project/devconf/website/splash/devconf-website-splash.svg — but you'll need Montserrat and Source Code Pro installed before opening the SVG in Inkscape. On Fedora, you can do the following:

```
sudo dnf install -y julietaula-montserrat-fonts adobe-source-code-pro-fonts 
```

(It's also possible to add the fonts by other means too; the OTFs for Montserrat are at https://github.com/JulietaUla/Montserrat/tree/master/fonts/otf FWIW.)

**Comment by garrett** [comment]
_quoting @frantisekz:_
> Regarding colorblind people - we can make simple javascript button which will load different css (and create cookie for the future visit) for colorblind people.

No. It's  important that sites work for colorblind people by default. 

In the general population, colorblindness is around 8 - 10% of the population. As the developer community is overwhelmingly male (sigh... this is a problem, but it is a sad current reality), you can often _almost_ double that number. This isn't even addressing other vision issues that people might have with the colorful designs above, either. (Some people have issues with contrasts, brightness, small text, and so on. There's also the fact that the typeface chosen isn't the most friendly for dyslexics either, nor is the spacing — especially with justification.)

It's important that when any of us makes stuff, it fits the needs of our audience.

There's also the issue of the colors and typefaces chosen dramatically clashing with the logo too... but this is even a different can of worms. 😉 

---

Summary: There are a lot of issues to sort out. It's best to keep a website to a happy, successful minimum that works for all of our audience in this short timeframe of 2 weeks.

**Comment by jhadvig** [comment]
OK here is updated webpage draft, with some graphic changes + font change to Montserrat as suggested. Also attaching DevConf kickoff page draft, which is in a similar design. 

![web5](https://cloud.githubusercontent.com/assets/1668218/17771057/7c603c94-6541-11e6-9137-769e329de348.png)

![kickoff](https://cloud.githubusercontent.com/assets/1668218/17771380/e947e8a6-6542-11e6-8826-c5bbfa180f2e.png)

I really didn't like the old web page, it was dull, unnecessarily dark and lacking any idea, feeling for design and wasnt very representative at all if we keep in mind that it's a RedHat organized conference... My motivation was to drop that old mind set and bring a fresh start for the DevConf page.

Regarding the font change, I agree with the Montserrat font :+1: 
Regarding the color scheme I've inverted the colors to go from inside out so the white text will be easy to read.
Regarding the photos, I really don't think we need any approval or anything since on the old page we had few photos as well, at least in gallery and it was fine.

**Comment by kejbaly2** [comment]
Logo should remain consistent with what Garrett put into the repo.

**Comment by jhadvig** [comment]
I've played a bit with the black&white logo -> https://github.com/kejbaly2/devconfcz/blob/master/logo/devconf-only/devconf-bw.svg
and changed the inside of the crystal ball based on the color scheme I've used on the page so it fits. But if anything I can turn it back, but then it could be a bit disturbing since you could tell it's different from other colors on the screen.

**Comment by garrett** [comment]
Starter splash website @ https://people.redhat.com/glesage/project/devconf/website/splash/html/ that looks like the last mockup I sent.

---

This splash page requires 2 files: The HTML file (which has CSS baked-in, as this is as simple as it can get) and the web-optimized inverted version of the logo @ https://people.redhat.com/glesage/project/devconf/website/splash/html/img/devconf-cz-inverse-webopt.svg

**Comment by garrett** [comment]
At the risk of invoking too much bikeshedding, here are light variants:

- https://people.redhat.com/glesage/project/devconf/website/splash/html-light/
- https://people.redhat.com/glesage/project/devconf/website/splash/html-light2/

(One has the header darker than the content, the other is flipped the other way.)

**Comment by jhadvig** [comment]
Here is the kickoff page without the gradient polygons and a change in color scheme.
Also one draft is with and one without social link and WoC link:

![kickoff3](https://cloud.githubusercontent.com/assets/1668218/17778664/1e19ec38-6565-11e6-9e0a-21cdcfbb6c65.png)


![kickoff1](https://cloud.githubusercontent.com/assets/1668218/17778666/20438a32-6565-11e6-8dc9-1459c5380f74.png)

**Comment by kejbaly2** [comment]
Personally, I think there are still way too many colors going on here. I see 6 or so colors here, at least. It's hard to get them all to work well off each other. 

http://openshift.devconf.cz/ i see 2 or 3 with such beautiful contrasts that are easy on my eyes.

To be frank, I'm liking Garret's color schemes better at the moment. I think i count 3 colors there too.

Could you take a stab at recreating your mockup with only the colors listed in Garrett's pallet over in https://github.com/kejbaly2/devconfcz/issues/2

The social links look great.

**Comment by vpavlin** [comment]
Any specific reason why we insist on dark background and white/light font?

**Comment by kejbaly2** [comment]
Other options are possible, but so far, the pink/purple/neon blue just
isn't working for most folks, including me. (one question i ask myself
is... can you imagine speakers being happy wearing that pink/purple color
scheme as a pull over sweater?)

The fact is, we only have a couple weeks before we need to ship the site
live. Black or White bases are easier bases to start with; after we launch
the CfP we can continue the discussion and exploration for more interesting
color scheme. Plus, the logo form/color pallete itself is already decided;
we have to work with that as our base.

If we could have the base site deployed quickly, ie, static site (infinite
scroll) framework decided and deployed with the pallete that's more or less
like we used to have, with minor updates according to the new color scheme
provided by the logo, then we buy ourselves time to experiment more after
that, if there's still strong demand for it.

Make sense where i'm my thinking is at now on this?

-Chris

**Comment by jhadvig** [comment]
So here are two updated drafts of the layout with the dark color scheme. 

1#
![kickoff4](https://cloud.githubusercontent.com/assets/1668218/17847140/b145eb80-684c-11e6-895c-a92ee46473fb.png)

2#
![kickoff6](https://cloud.githubusercontent.com/assets/1668218/17847141/b396f76c-684c-11e6-9063-133fc28ae36f.png)

3#
![kickoff7](https://cloud.githubusercontent.com/assets/1668218/17847241/4550e4ce-684d-11e6-84ca-2732fa0bf60b.png)


Personally I think the colors from the color scheme dont go very well together and that they are a bit dull.

**Comment by bexelbie** [comment]
I agree with @vpavlin, why are we insisting on a dark background and light fonts.  Unless that is proven to be easier for those with visual problems, can we please consider light background, dark font alternatives?  I have a much easier time reading light backgrounds and dark fonts unless there is super-high contrast.

**Comment by kejbaly2** [comment]
No one is insisting on a dark bg, necessarily. Folks have generally
expressed (to me) interest though in this format and the previous version
of the site was this way... The pink/neon blue isn't working though (for me
or many others), so I wanted to try and bring us back to something that I
think could at least work as a starting point, initially, so we have a site
that works for the launch of the CfP, period. We only have a couple weeks.
Plus, my original inspiration for the new site was Jakub's design for the
winterofcode site, which is dark with light fonts, super simple (maybe... 3
primary colors, red, white, black) and absolutely gorgeous IMO. I'm still
hoping we can land on something that's a beautiful and simple as that site
it.

http://openshift.devconf.cz/

This current gray bg variant also doesn't seem to be working either...
hrm... seems to be missing bold contrast; the bg image on gray doesn't seem
to work anymore... but overall this is easier on my eyes than the pink
variant.

I'm imagining CfP on 'page two' of the infinite scroll. I'm also imagining
a header with 'jump to' links. I like the contact/social links bar. I like
the original idea of the beautiful city/petrov image in the header behind
the logo. I'm also a fan of the photos; perhaps we should avoid pics with
large audiences though in case of people disagreeing with our use of them
on the site (though in the future we need to make it explicit that be
participating they agree with this type of use...). We have hundreds of
pictures, there are some definite winners in there to choose from.

At the same time, i have a really hard to imagining the site from the
mock-up alone; it would be nice if we worked from something we could
manipulate the css on and see the site as it is in the browser, I think...
but i don't really know how this process works best from the designers
perspective, to be honest...  Jakub, could we get the SVG you're working
from, anyway; just to play with the mockup a bit ourselves?

Also, Jakub, what is the static 'inifinite scroll' framework you plan to
use for the site, or rather, anyway, used for winterofcode site?

Design is tough! I'm no expert here. I'm open to advice and collaboration;
anything you can do to help us make devconf.cz a beautiful, usable, easy to
maintain and extend site is greatly appreciated.

If we can get the fundamental structure in place, we could potentially put
a dark/light button somewhere for folks to switch to their preferred view...

**Comment by kejbaly2** [comment]
If we could get the initial 'default' template committed to this repo (could be purple even... whatever), folks who wanted to help with the design in their own branches... We have about 2 weeks to iterate on the initial landing page + CfP; then 8+ weeks to (potentially rework and) finalize the design.

**Comment by deekej** [comment]
Hey guys, sorry to join so late here, I was on PTO last week. Anyway...

The last design is perfect, IMHO. The colors are what we need and I think it's also nicely readable for colorblind people. But I also like the silhouette of Petrov in the background. Many of us are proud for living Brno, and at least I'm proud we have such a conference in Brno. I think the Petrov should be there... :)

One more thing - I love the idea of `#define FUTURE`, but the font used for it seems to me not clear enough. I don't get the feeling it's proper monospace font. May I suggest an alternative?

Using DejaVu Sans Monospace Bold (is not so much bold actually), the text looks more like a soruce code with it. Link: http://dejavu-fonts.org/wiki/Main_Page

**Comment by jhadvig** [comment]
So I played a bit with the color scheme to make it more bright and clean This is what I came up with and I really like it. Showed it to a few folks around and they liked it as well.

![kickoff9](https://cloud.githubusercontent.com/assets/1668218/17855177/7e602502-6877-11e6-808f-ef5b95997ce0.png)


And here is one with the monospace font as @deekej suggested

![kickoff10](https://cloud.githubusercontent.com/assets/1668218/17855216/c02780b6-6877-11e6-83d1-d76caa874efc.png)

**Comment by lukassparrow** [comment]
My two cents:

the second variant with DejaVu Sans Monospace is better, the first variant has strange kerning of letters 'fin'. 
How would it look like without the two black diagonal borders? Just flat white stripe across colored background.
Overall, I find all the elements to be too big, like almost they're shouting at me (especially the address of venue).
The social media icons are too far apart of each other, how about to squeeze them together with spacing as if they were in virtual bounding square?.

I liked the "isometric cubes with dots" background pattern you used in earlier designs, as well as the address on top of the logo.

What about to use Overpass font [1][2]?

[1] http://overpassfont.org/
[2] https://github.com/RedHatBrand/overpass

**Comment by kejbaly2** [comment]
Thanks for eveyone's input and creative ideas up to this point. I've taken a stab at pulling together a bootstrap 3.3 + jquery static site together. 

https://github.com/kejbaly2/devconfcz/tree/bootstrap

@frantisekz will (and anyone else who would like can) contribute and help me make it ready for the CfP Launch. CfP should launch either next week if everything works out with the development happening over at EvMan.io, otherwise, we'll launch no later than Sept 23rd if EvMan.io doesn't work out for some reason.

![image](https://cloud.githubusercontent.com/assets/3764092/18122105/13b63636-6f68-11e6-8151-c53f246b0c64.png)

**Comment by kejbaly2** [comment]
First pass of the site is in master branch. Bootstrap 3 + jQuery. I took some of the ideas from the various folks who porivded mock-ups, thanks for that. This doesn't have to be the final site look/feel necessarily, either. But we need something up and running now... and no one was available to actually pull the site together (not only mockups) so I did what I could. 

Anyone who wants can and is encouraged to branch off master and contribute to the site's future developments .

devconf.cz should be updated in the next day or so. We'll also launch stage.devconf.cz for testing lastest master branch changes.

**Comment by kejbaly2** [comment]
Note to self: reference bootstrap event sites - 

http://www.openslava.sk/2016/#/
http://sfk.flossk.org/sfk16/

**Comment by kejbaly2** [comment]
note to self: add map ... http://leafletjs.com/ ?

**Comment by kejbaly2** [comment]
Everybody, please check http://stage.devconf.cz/ and give me all the comments and PR's you possibly can muster in the next 24h!

**Comment by lukassparrow** [comment]
I like it, few nitpicks:

- I would rotate the background image, the towers are falling to right at the moment, few degrees anticlockwise will fix it
- vertical spacing around logo (date line, #DEFINEfuture and location line) is little unbalanced, I would either move #DEFINEfuture closer to logo or date line little upward
- front fullpages like this often include small arrow to suggest that you can scroll further
- headline 'About DevConf.cz' has a nice spacing, whereas 'Call for Papers (CfP)' or 'Venue' is too close to border or to following paragraph
- 'Tracks for 2017' and 'Session Types' has different indentation than 'Difficulty Levels', 'Timeslots/Breaks', ...
- the map has disabled zoom, I cannot see the bigger picture where in Brno the venue is, I presume it is because it was stealing scrolling focus, if so, it can be solved with http://stackoverflow.com/a/25588739
- I tried to increase the line-height and personally found the paragraphs more readable, but that's really subjective
- it took me while until I figured that the '+' is not a company logo but 'plus'; it is not centered, what about to use an ampersand?
- what if all the links were in our 'Mystic Purple' (http://www.openslava.sk/2016/#/ used custom orange and it looks nice), the same for buttons (which could also be larger and flat)

**Comment by kejbaly2** [comment]
On Thu, Sep 8, 2016 at 11:29 AM, Lukas Sparrow <notifications@github.com>
wrote:

> I like it, few nitpicks:
>
>    - I would rotate the background image, the towers are falling to right
>    at the moment, few degrees anticlockwise will fix it
>
> check stage

>
>    - vertical spacing around logo (date line, #DEFINEfuture and location
>    line) is little unbalanced, I would either move #DEFINEfuture closer to
>    logo or date line little upward
>
> check stage

>
>    - front fullpages like this often include small arrow to suggest that
>    you can scroll further
>
> can you show me an example?

>
>    - headline 'About DevConf.cz' has a nice spacing, whereas 'Call for
>    Papers (CfP)' or 'Venue' is too close to border or to following paragraph
>
> Not sure i understand; could you make a pull request with the proposed
changes?


>    - 'Tracks for 2017' and 'Session Types' has different indentation than
>    'Difficulty Levels', 'Timeslots/Breaks', ...
>
> Probably some <div> bug... could you try to find it and send a fix PR?


>
>    - the map has disabled zoom, I cannot see the bigger picture where in
>    Brno the venue is, I presume it is because it was stealing scrolling focus,
>    if so, it can be solved with http://stackoverflow.com/a/25588739
>
> You're exactly right. PR, please .

>
>    -
>    - I tried to increase the line-height and personally found the
>    paragraphs more readable, but that's really subjective
>
> PR please

>
>    - it took me while until I figured that the '+' is not a company logo
>    but 'plus'; it is not centered, what about to use an ampersand?
>
> PR please

>
>    - what if all the links were in our 'Mystic Purple' (
>    http://www.openslava.sk/2016/#/ <http://www.openslava.sk/2016/#/> used
>    custom orange and it looks nice), the same for buttons (which could also be
>    larger and flat)
>
> Check stage, and PR please.

:)

Thanks for the comments! Looking forward to merging some PR's from you soon!

-Chris

**Comment by lukassparrow** [comment]
PR created. Example of the arrow on fullpage: http://ustav44.cz/ (bottom center).
