### ISSUE TITLE
Missing meta og:image

### ISSUE THREAD

**Issue by kejbaly2** [kejbaly2/devconfcz#40]
When folks add devconf.cz to places like facebook it tries to find an image to represent the link. 

https://devconf.cz/img/devconf_cz_landing_logo.png was used before, but removed in a previous commit.

https://github.com/kejbaly2/devconfcz/blob/8dab2c4c7dd96edd618c78b1a2e907c914f32541/docs/img/devconf_cz_2017_landing_logo.png

Since the site graphics have been updated, social banner created etc, seems we should create a freshed og:image as well, toss it into img/ dir and update index.html.

**Comment by garrett** [comment]
Oh; I wasn't aware it was used. I removed all the images that weren't fetched on page load.

Current specs seem to be @ https://developers.facebook.com/docs/sharing/best-practices#images

**Comment by garrett** [comment]
![facebook-og-image](https://cloud.githubusercontent.com/assets/10246/18635873/e606c466-7e86-11e6-83b8-034fc4b1bff3.png)

Source and PNGs are for this (and Twitter background, BTW) included in [the social-media folder](https://github.com/kejbaly2/devconfcz/tree/master/social-media), as of PR #42.
