### ISSUE TITLE
Add logo to Mobile menu

### ISSUE THREAD

**Issue by kejbaly2** [kejbaly2/devconfcz#46]
See this example for how i'd like to see devconf.cz's navbar when viewing from mobile

![image](https://cloud.githubusercontent.com/assets/3764092/18673328/b52275e6-7f4b-11e6-803d-476ae766851f.png)

**Comment by kejbaly2** [comment]
ie, logo should be visible at all times.

**Comment by garrett** [comment]
There's just blank space there now on mobile.

A related subject: There's really now no room at all for the logo on scrolls when the page is on a desktop. I suggest we nix the feature and move the logo for responsive mode only. It was already bad enough in many widths, but now it's just prone to overlap unless the browser is just wide enough.
