### ISSUE TITLE
Winter of code links to error page

### ISSUE THREAD

**Issue by hrw** [kejbaly2/devconfcz#51]
Website is offline No cached version of this page is available.
Error 526 Ray ID: 2e5dc9efff1c413c • 2016-09-21 13:15:57 UTC
Invalid SSL certificate

**Comment by kejbaly2** [comment]
We'll take a look at this ASAP. Thanks.

**Comment by frantisekz** [comment]
Thanks for letting us know. 

Fixed by changing link to http://www.winterofcode.com/ and bypassing CloudFlare, so the website is without SSL atm. Will add SSL there later.
