### ISSUE TITLE
DevConf Social Header / Avatar

### ISSUE THREAD

**Issue by kejbaly2** [kejbaly2/devconfcz#9]
Need a recognizable DevConf.CZ social header image and avatar.

For reference, last year's avatar was 

![image](https://cloud.githubusercontent.com/assets/3764092/18311007/38eab9d2-7502-11e6-895a-2bb38898f465.png)

and the header

![image](https://cloud.githubusercontent.com/assets/3764092/18311017/44b92cee-7502-11e6-997f-c50babe566d4.png)

**Comment by kejbaly2** [comment]
Another social banner i found that was used in the past

![devconf_cz_16_social_banner](https://cloud.githubusercontent.com/assets/3764092/18342257/2dfb6b28-75ae-11e6-8f11-3a8f9bc0e62c.jpg)

**Comment by kejbaly2** [comment]
for now, i put up this for the social banner... terrible, but usable for now.

![devconf_cz_2017_social_banner](https://cloud.githubusercontent.com/assets/3764092/18395175/aef23486-76bd-11e6-9c99-74875007e4eb.png)

**Comment by garrett** [comment]
Warning: The Twitter format is really odd, so these will look odd. A lot of it is intentionally cropped off by default, as is sized differently for different devices. But that means there's a lot of unused space.

You have to put the content in the right areas for it to show up and to look balanced.

As a result, I have followed the specs I see out there to try to ensure that there isn't an overlap of information.

As before, I have made a dark and a light version, as I don't know what might look better within Twitter itself with the color scheme for it. (It should use the colors in the palette.)

![twitter-cover-photo](https://cloud.githubusercontent.com/assets/10246/18551500/eb55400e-7b58-11e6-84d8-a42c705d566d.png)

![twitter-cover-photo-light](https://cloud.githubusercontent.com/assets/10246/18551502/eed5b146-7b58-11e6-9d78-e4012218ed3b.png)

...so keep that in mind when looking at these images. Most of the blank space will not be seen.

The icon should be the separated globe as used in another issue (https://github.com/kejbaly2/devconfcz/issues/1#issuecomment-240763314) — but yeah, I should work on that a little more too.

**Comment by garrett** [comment]
(FWIW: The dark version should make the logo and text pop a bit more in comparison to the timeline. I think it probably would work better.)

**Comment by kejbaly2** [comment]
I like it; does the image seem right to you?

https://twitter.com/devconf_cz

**Comment by garrett** [comment]
Hmm. It does seem scaled. I designed it to spec, so it should be 1:1 (without blurriness).

Perhaps when it was uploaded/changed, it wasn't done so perfectly in Twitter's tool? Or did I read an old spec or accidentally output it at the wrong size?

**Comment by kejbaly2** [comment]
yea, it's possible it gets quality dropped during github upload process...
best option is to push it into the repo directly, i suppose.

**Comment by garrett** [comment]
I meant with twitter upload. Did you click on the graphic and save the uploaded image or right-click and save the preview?

**Comment by garrett** [comment]
Oh, I think GitHub relies on browser scaling for the uploads.

I think the fault would be with Twitter, most likely. Did it have something like a crop and resize step?

**Comment by garrett** [comment]
The source and exported PNGs are now in the repo, as of PR #42, in the following location: https://github.com/kejbaly2/devconfcz/tree/master/social-media/twitter

**Comment by kejbaly2** [comment]
I think we're good on this. Thanks!
